name: Publish to @next

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  job_1:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"

      - name: Install packages
        run: npm i

      - name: ESLint
        run: sudo npx eslint .

      - name: TSC
        if: always()
        run: sudo npx tsc

  job_2:
    name: Publish to @next
    runs-on: ubuntu-latest
    needs: [job_1]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: Increment version
        run: node scripts/increment-version-next.js

      - name: Update lockfile
        run: npm i

      - name: Prettify
        run: sudo npm run prettier

      - name: Publish to npm registry
        run: npm publish --tag next --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get new package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Commit package.json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ steps.package-version.outputs.current-version}}
          commit_author: "github-actions <actions@github.com>"
